"""
Session State - Centralized State Management

The SYSTEM owns context, not the AI models.
All models are stateless workers that receive context from State.
"""
from typing import Dict, Any, Optional, List
from datetime import datetime
from dataclasses import dataclass, field
from enum import Enum
import json
import uuid


class BranchStatus(Enum):
    ACTIVE = "active"
    PAUSED = "paused"
    SUMMARIZED = "summarized"
    COMPLETED = "completed"


class ObjectLifecycle(Enum):
    ACTIVE = "active"        # Visible, referenceable
    HIDDEN = "hidden"        # Not visible, can be recalled
    ARCHIVED = "archived"    # Removed from active State


@dataclass
class VisualObject:
    """
    A visual object that appears in animations.
    Object IDs are assigned by Orchestrator, not by LLMs.
    """
    object_id: str
    object_type: str                      # curve, point, vector, label, etc.
    manim_class: str                      # ParametricFunction, Arrow, MathTex, etc.
    display_name: str                     # "the yellow curve", "f(x)"
    alternative_names: List[str]          # ["the parabola", "your function"]
    color: str                            # hex color
    properties: Dict[str, Any]            # Additional Manim properties
    created_at_scene: str                 # scene_id where created
    visible_in_scenes: List[str]          # which scenes show this object
    lifecycle: ObjectLifecycle = ObjectLifecycle.ACTIVE
    position: Optional[List[float]] = None  # [x, y] or center
    bounding_box: Optional[List[List[float]]] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "object_id": self.object_id,
            "object_type": self.object_type,
            "manim_class": self.manim_class,
            "display_name": self.display_name,
            "alternative_names": self.alternative_names,
            "color": self.color,
            "properties": self.properties,
            "created_at_scene": self.created_at_scene,
            "visible_in_scenes": self.visible_in_scenes,
            "lifecycle": self.lifecycle.value,
            "position": self.position,
            "bounding_box": self.bounding_box
        }


@dataclass
class Scene:
    """A single animation scene with visual objects and narration."""
    scene_id: str
    scene_number: int
    concept: str                          # What this scene teaches
    manim_code: Optional[str]             # Generated by Qwen
    video_path: Optional[str]             # Rendered video segment
    duration_seconds: float
    visual_objects: List[str]             # object_ids in this scene
    narration_text: str                   # What to say during this scene
    animation_sequence: List[Dict[str, Any]]  # Animation steps
    status: str = "pending"               # pending, rendering, completed, failed

    def to_dict(self) -> Dict[str, Any]:
        return {
            "scene_id": self.scene_id,
            "scene_number": self.scene_number,
            "concept": self.concept,
            "video_path": self.video_path,
            "duration_seconds": self.duration_seconds,
            "visual_objects": self.visual_objects,
            "narration_text": self.narration_text,
            "animation_sequence": self.animation_sequence,
            "status": self.status
        }


@dataclass
class Branch:
    """
    A conversation branch when user asks follow-up question.
    Max depth = 3 active branches (older auto-summarized).
    """
    branch_id: str
    parent_branch_id: Optional[str]
    depth: int
    trigger_message: str                  # What user asked to create this branch
    status: BranchStatus
    scene_ids: List[str]                  # Scenes created in this branch
    summary: Optional[str] = None         # Auto-generated when summarized
    created_at: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "branch_id": self.branch_id,
            "parent_branch_id": self.parent_branch_id,
            "depth": self.depth,
            "trigger_message": self.trigger_message,
            "status": self.status.value,
            "scene_ids": self.scene_ids,
            "summary": self.summary,
            "created_at": self.created_at.isoformat()
        }


@dataclass
class ConversationMessage:
    """A single message in the conversation."""
    message_id: str
    role: str                             # user, assistant
    content: str
    timestamp: datetime
    branch_id: Optional[str] = None
    triggered_video: bool = False
    video_job_id: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "message_id": self.message_id,
            "role": self.role,
            "content": self.content,
            "timestamp": self.timestamp.isoformat(),
            "branch_id": self.branch_id,
            "triggered_video": self.triggered_video,
            "video_job_id": self.video_job_id
        }


@dataclass
class SessionState:
    """
    Complete session state - the single source of truth.
    
    All models receive context FROM this state.
    All models write results TO this state (via Orchestrator).
    No model has internal memory.
    """
    session_id: str
    user_id: Optional[str]
    topic_root: str                       # Main topic being taught
    created_at: datetime
    last_activity: datetime
    
    # Conversation
    messages: List[ConversationMessage] = field(default_factory=list)
    
    # Scene tree
    scenes: Dict[str, Scene] = field(default_factory=dict)
    scene_order: List[str] = field(default_factory=list)  # Ordered scene_ids
    
    # Visual objects (session-scoped IDs)
    visual_objects: Dict[str, VisualObject] = field(default_factory=dict)
    object_counter: int = 0               # For generating unique IDs
    
    # Branching
    branches: Dict[str, Branch] = field(default_factory=dict)
    current_branch_id: Optional[str] = None
    max_branch_depth: int = 3
    
    # Focus tracking
    focus_object_ids: List[str] = field(default_factory=list)
    
    # Video state
    current_video_job_id: Optional[str] = None
    assembled_video_path: Optional[str] = None
    
    # Persistence
    checkpoint_version: int = 0
    
    @classmethod
    def create_new(cls, topic: str, user_id: Optional[str] = None) -> 'SessionState':
        """Create a new session state."""
        session_id = f"sess_{uuid.uuid4().hex[:12]}"
        now = datetime.now()
        
        # Create root branch
        root_branch = Branch(
            branch_id="branch_root",
            parent_branch_id=None,
            depth=0,
            trigger_message=topic,
            status=BranchStatus.ACTIVE,
            scene_ids=[]
        )
        
        return cls(
            session_id=session_id,
            user_id=user_id,
            topic_root=topic,
            created_at=now,
            last_activity=now,
            branches={"branch_root": root_branch},
            current_branch_id="branch_root"
        )
    
    def generate_object_id(self) -> str:
        """Generate a unique, session-scoped object ID."""
        self.object_counter += 1
        return f"{self.session_id}_obj_{self.object_counter:04d}"
    
    def generate_scene_id(self) -> str:
        """Generate a unique scene ID."""
        scene_num = len(self.scenes) + 1
        return f"S{scene_num}"
    
    def add_message(self, role: str, content: str, video_job_id: Optional[str] = None) -> ConversationMessage:
        """Add a message to conversation history."""
        msg = ConversationMessage(
            message_id=f"msg_{uuid.uuid4().hex[:8]}",
            role=role,
            content=content,
            timestamp=datetime.now(),
            branch_id=self.current_branch_id,
            triggered_video=video_job_id is not None,
            video_job_id=video_job_id
        )
        self.messages.append(msg)
        self.last_activity = datetime.now()
        return msg
    
    def add_visual_object(
        self,
        object_type: str,
        manim_class: str,
        display_name: str,
        color: str,
        scene_id: str,
        properties: Optional[Dict[str, Any]] = None,
        alternative_names: Optional[List[str]] = None
    ) -> VisualObject:
        """Add a visual object to the state. ID is assigned by Orchestrator."""
        obj = VisualObject(
            object_id=self.generate_object_id(),
            object_type=object_type,
            manim_class=manim_class,
            display_name=display_name,
            alternative_names=alternative_names or [],
            color=color,
            properties=properties or {},
            created_at_scene=scene_id,
            visible_in_scenes=[scene_id]
        )
        self.visual_objects[obj.object_id] = obj
        return obj
    
    def add_scene(
        self,
        concept: str,
        narration_text: str,
        duration_seconds: float,
        visual_object_ids: Optional[List[str]] = None,
        manim_code: Optional[str] = None
    ) -> Scene:
        """Add a scene to the timeline."""
        scene_id = self.generate_scene_id()
        scene = Scene(
            scene_id=scene_id,
            scene_number=len(self.scenes) + 1,
            concept=concept,
            manim_code=manim_code,
            video_path=None,
            duration_seconds=duration_seconds,
            visual_objects=visual_object_ids or [],
            narration_text=narration_text,
            animation_sequence=[]
        )
        self.scenes[scene_id] = scene
        self.scene_order.append(scene_id)
        
        # Add to current branch
        if self.current_branch_id and self.current_branch_id in self.branches:
            self.branches[self.current_branch_id].scene_ids.append(scene_id)
        
        return scene
    
    def get_active_objects(self) -> List[VisualObject]:
        """Get all currently active visual objects."""
        return [
            obj for obj in self.visual_objects.values()
            if obj.lifecycle == ObjectLifecycle.ACTIVE
        ]
    
    def get_recent_messages(self, count: int = 10) -> List[ConversationMessage]:
        """Get the most recent messages for context."""
        return self.messages[-count:] if len(self.messages) > count else self.messages
    
    def get_current_branch_depth(self) -> int:
        """Get the current branch depth."""
        if not self.current_branch_id or self.current_branch_id not in self.branches:
            return 0
        return self.branches[self.current_branch_id].depth
    
    def to_dict(self) -> Dict[str, Any]:
        """Serialize state to dictionary."""
        return {
            "session_id": self.session_id,
            "user_id": self.user_id,
            "topic_root": self.topic_root,
            "created_at": self.created_at.isoformat(),
            "last_activity": self.last_activity.isoformat(),
            "messages": [m.to_dict() for m in self.messages],
            "scenes": {k: v.to_dict() for k, v in self.scenes.items()},
            "scene_order": self.scene_order,
            "visual_objects": {k: v.to_dict() for k, v in self.visual_objects.items()},
            "branches": {k: v.to_dict() for k, v in self.branches.items()},
            "current_branch_id": self.current_branch_id,
            "focus_object_ids": self.focus_object_ids,
            "current_video_job_id": self.current_video_job_id,
            "assembled_video_path": self.assembled_video_path,
            "checkpoint_version": self.checkpoint_version
        }
    
    def to_json(self) -> str:
        """Serialize state to JSON string."""
        return json.dumps(self.to_dict(), indent=2)
    
    def checkpoint(self) -> None:
        """Increment checkpoint version for persistence."""
        self.checkpoint_version += 1
        self.last_activity = datetime.now()
